# для PnP (позволяет опираться на файл .pnp.cjs, который указывает путь к пакетам в кеше,
# а не на node_modules)
nodeLinker: pnp
# для zero-installs (кеш с пакетами хранится локально в проекте, а не глобально в системе)
enableGlobalCache: false
